### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by flaming0** [AbeEstrada/atom-hex#15]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.182.0
**System**: linux 3.16.0-30-generic
**Thrown From**: [hex](https://github.com/AbeEstrada/atom-hex) package, v0.5.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/flamingo/.atom/packages/hex/lib/hex.coffee:24

TypeError: undefined is not a function
  at createView (/home/flamingo/.atom/packages/hex/lib/hex.coffee:24:23)
  at atom-workspace.<anonymous> (/home/flamingo/.atom/packages/hex/lib/hex.coffee:9:56)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:69:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
     -7:44.6 editor:indent (atom-text-editor.editor)
     -7:44.4 snippets:next-tab-stop (atom-text-editor.editor)
     -7:44.4 snippets:expand (atom-text-editor.editor)
     -7:44.4 editor:indent (atom-text-editor.editor)
     -7:42.5 core:save (atom-text-editor.editor)
     -1:50.3 grammar-selector:show (atom-text-editor.editor)
     -1:47.2 editor:consolidate-selections (atom-text-editor.editor.mini)
  2x -1:47.2 core:cancel (atom-text-editor.editor.mini)
     -1:45.5 settings-view:open (a.inline-block)
     -1:38.7 core:confirm (atom-text-editor.editor.mini)
     -1:10.0 grammar-selector:show (atom-text-editor.editor)
     -1:07.3 editor:consolidate-selections (atom-text-editor.editor.mini)
  2x -1:07.3 core:cancel (atom-text-editor.editor.mini)
     -1:05.4 settings-view:open (atom-text-editor.editor)
     -0:29.9 grammar-selector:show (atom-text-editor.editor)
     -0:00.7 hex:view (div.settings-view.pane-item)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  },
  "hex": {}
}
```

### Installed Packages

```coffee
# User
hex, v0.5.0
language-x86asm, v0.4.0
script, v2.16.0
trailing-spaces, v0.2.4

# Dev
No dev packages
```

**Comment by AbeEstrada** [comment]
@flaming0 are you still having this issue with the latest version?

**Comment by slobodin** [comment]
No.
